cargo-features = ["edition2024"]

[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "2.2.1"

[lib]
name = "hello_world_v2"
crate-type = ["cdylib", "lib"]